params:
  docs:
    hide_folders:
      - crds
      - design
    external_docs:
      - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
        name: v0.30.0
        branch: v0.30.0
        dir: docs
      - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
        name: v0.29.0
        branch: v0.29.0
        dir: docs
      - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
        name: v0.28.1
        branch: v0.28.1
        dir: docs
      - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
        name: latest
        branch: main
        dir: docs
