params:
  docs:
    hide_folders:
    - crds
    - design
    external_docs:
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: v0.40.0
      branch: v0.40.0
      dir: docs
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: v0.39.0
      branch: v0.39.0
      dir: docs
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: v0.38.1
      branch: v0.38.1
      dir: docs
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: latest
      branch: main
      dir: docs
